config/routes.rb
Rails.application.routes.draw do
  
  # get 'user/update'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  # Routes for STI api_params
  resources :helpscout_params, controller: 'api_params', type: 'HelpscoutParam'
  resources :hotmart_params, controller: 'api_params', type: 'HotmartParam'
  resources :mailchimp_params, controller: 'api_params', type: 'MailchimpParam'

  # Routes for STI api_keys
  resources :helpscout_api_keys, controller: 'api_keys', type: 'HelpscoutApiKey', only: [:edit, :update]
  resources :hotmart_api_keys, controller: 'api_keys', type: 'HotmartApiKey', only: [:edit, :update]
  resources :mailchimp_api_keys, controller: 'api_keys', type: 'MailchimpApiKey', only: [:edit, :update]

  resources :activation_rules
  get "/mailchimp_actuation_rules/load_group_names", to: 'mailchimp_actuation_rules#load_group_names'
  resources :mailchimp_actuation_rules
  resources :rule_associations

  resources :notifications, only: [:index, :show, :destroy]
  post "/notifications/:token", to: 'notifications#create'
  post "/helpscout_info/:token", to: 'helpscout_info#get_notification', as: 'helpscout_info'

end

app/models/api_key.rb
# == Schema Information
#
# Table name: api_keys
#
#  id         :integer          not null, primary key
#  key        :string(255)
#  validated  :boolean
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  type       :string(255)
#

class ApiKey < ActiveRecord::Base
  
  # scopes for inherited models
  scope :helpscout_api_key, -> { where(type: 'HelpscoutApiKey') } 
  scope :hotmart_api_key, -> { where(type: 'HotmartApiKey') } 
  scope :mailchimp_api_key, -> { where(type: 'MailchimpApiKey') }

  belongs_to :user
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  layout 'client'

  before_action :set_api_name
  before_action :set_api_key_obj, only: [:edit, :update]

  def edit
  end

  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to script_api_path(@api_name, @api_key, :edit),
                                  notice: "Chave atualizada com sucesso." }
        format.json { render :show,
                              status: :ok,
                              location: @api_key }
      else
        format.html { render :edit }
        format.json { render json: @api_key.errors,
                              status: :unprocessable_entity }
      end
    end
  end

  private

  def api_key_params
    params.require(get_api_key_name.underscore.to_sym).permit(:key)
  end

  def set_api_name
    @api_name = get_api_key_name
  end

  def get_api_key_name
    ApiKey.descendants.map { |api_key| api_key.to_s }.
                        include?(params[:type]) ? params[:type] : 'HotmartApiKey'
  end

  def api_class
    get_api_key_name.constantize
  end

  def set_api_key_obj
    @api_key = current_user.
                send(params[:type].underscore).
                try(:first)
  end

end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
  def active_tab(api)
    return true if api == params[:type]
  end
end

app/views/api_keys/_form.html.erb
<%= simple_form_for @api_key, :html => { :class => "form-inline" },
  wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean
  } do |f| %>

  <div class="col-sm-7" id="key">
    <%= f.input :key, :input_html => { :size => 43 } %>
    <%= fa_icon('check-circle 3x', class: 'icon-green', id: 'validated') if @api_key.validated? %>
    <%= f.submit nil, :class => 'btn btn-primary', value: 'Update' %>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class=<%= "active" if active_tab('HotmartApiKey') %>>
    <%= link_to t('api.hotmart'),
                edit_hotmart_api_key_path(current_user.hotmart_api_key.first.id),
                id: 'hotmart_api_key_area' %>
  </li>
  <li class=<%= "active" if active_tab('MailchimpApiKey') %>>
    <%= link_to t('api.mailchimp'),
                edit_mailchimp_api_key_path(current_user.mailchimp_api_key.first.id),
                id: 'mailchimp_api_key_area' %>
  </li>
  <li class=<%= "active" if active_tab('HelpscoutApiKey') %>>
    <%= link_to t('api.helpscout'),
                edit_helpscout_api_key_path(current_user.helpscout_api_key.first.id),
                id: 'helpscout_api_key_area' %>
  </li>
</ul>

<% if request.path =~ /^\/hotmart_api_keys\// %>
  <div id="hotmart_callback" class="col-sm-7">
    <mark><%= notification_url(current_user.hotmart_token) %></mark>
  </div>
  <br />
<% end %>
<% if request.path =~ /^\/helpscout_api_keys\// %>
  <div id="helpscout_callback" class="col-sm-7">
    <mark><%= helpscout_info_url(current_user.helpscout_token) %></mark>
  </div>
  <br />
<% end %>
<%= render :partial => 'form' %>