config/routes.rb
Rails.application.routes.draw do
  
  # get 'user/update'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  # Routes for STI api_params
  resources :helpscout_params, controller: 'api_params', type: 'HelpscoutParam'
  resources :hotmart_params, controller: 'api_params', type: 'HotmartParam'
  resources :mailchimp_params, controller: 'api_params', type: 'MailchimpParam'

  # Routes for STI api_keys
  resources :helpscout_api_keys, controller: 'api_keys', type: 'HelpscoutApiKey', only: [:edit, :update]
  resources :hotmart_api_keys, controller: 'api_keys', type: 'HotmartApiKey', only: [:edit, :update]
  resources :mailchimp_api_keys, controller: 'api_keys', type: 'MailchimpApiKey', only: [:edit, :update]

  resources :activation_rules
  get "/mailchimp_actuation_rules/load_group_names", to: 'mailchimp_actuation_rules#load_group_names'
  resources :mailchimp_actuation_rules
  resources :rule_associations

  resources :notifications, only: [:index, :show, :destroy]
  post "/notifications/:token", to: 'notifications#create'
  post "/helpscout_info/:token", to: 'helpscout_info#get_notification', as: 'helpscout_info'

end

app/models/activation_rule.rb
# == Schema Information
#
# Table name: activation_rules
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  name        :string(255)
#  description :text(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class ActivationRule < ActiveRecord::Base
  validates_presence_of :name, :description
  validates_uniqueness_of :name, scope: :user_id
  
  belongs_to :user
  has_many :notifications
  has_many :rule_associations
  has_many :mailchimp_actuation_rules ,through: :rule_associations

  has_many :activation_params, dependent: :destroy
  has_many :api_params, :through => :activation_params
  accepts_nested_attributes_for :activation_params#, :reject_if => lambda { |c| c[:value].blank? }

  # Dentro do ActivationRule model
  def activated?(params)
    date_min = nil
    date_max = nil

    self.activation_params.each do |parametro|
      if(parametro.api_param.name == "purchase_date_start" && parametro.value.downcase.to_date)
        date_min = parametro.value.downcase.to_date
        return false if date_min > params[:purchase_date].to_date
      elsif(parametro.api_param.name == "purchase_date_end" && parametro.value.downcase.to_date)
        date_max = parametro.value.downcase.to_date
        return false if date_max < params[:purchase_date].to_date
      else
        return false unless parametro.value.downcase == params[parametro.api_param.name].try(:downcase) ||
                            parametro.value == "" # Garante que parâmetros não preenchidos sejam ignorados
      end
    end

    return true
  end

  def self.duplicate(id)
    attrs = self.find_by_id(id).attributes
    obj = self.new(attrs)
    obj.activation_params.each { |ap| ap.id = nil }
    obj
  end
end

app/controllers/activation_rules_controller.rb
class ActivationRulesController < ApplicationController
  layout 'client'
  before_action :set_rule_name
  before_action :set_activation_rule, only: [:show, :edit, :update, :destroy]
  before_action :check_whether_api_key_was_created

  # GET /rules
  # GET /rules.json
  def index
    @activation_rules = current_user.activation_rules
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    if params[:id].blank?
      @activation_rule = ActivationRule.new
      @activation_rule.api_params = HotmartParam.allowed_in_activation_rule
    else
      @activation_rule = ActivationRule.duplicate(params[:id])
      # @activation_rule = ActivationRule.new(ActivationRule.find_by_id(params[:id]).attributes)
      # @activation_rule.activation_params.each do |ap|
      #   ap.id = nil
      # end
    end
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @activation_rule = ActivationRule.new(activation_rule_params)
    @activation_rule.user = current_user

    respond_to do |format|
      if @activation_rule.save
        format.html { redirect_to @activation_rule,
                                  notice: 'Regra criada com sucesso' }
        format.json { render :show,
                              status: :created,
                              location: @activation_rule }
      else
        format.html { render :new }
        format.json { render json: @activation_rule.errors,
                              status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @activation_rule.update(activation_rule_params)
        format.html { redirect_to @activation_rule,
                                  notice: 'Regra atualizada com sucesso' }
        format.json { render :show,
                              status: :ok,
                              location: @activation_rule }
      else
        format.html { render :edit }
        format.json { render json: @activation_rule.errors,
                                    status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @activation_rule.destroy
    respond_to do |format|
      format.html { redirect_to activation_rules_url,
                                notice: 'Regra excluída com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def check_whether_api_key_was_created
    apiKeyObj = current_user.hotmart_api_key.first
    redirect_to edit_hotmart_api_key_path(apiKeyObj.id),
        alert: "Para acessar esta área informe abaixo \
                  seu token do Hotmart." if apiKeyObj.key.blank?
  end

  def set_rule_name
    @activation_rule_name = get_activation_rule_name
  end

  def get_activation_rule_name
    ActivationRule.to_s
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_activation_rule
    @activation_rule = current_user.activation_rules.find_by_id(params[:id])
    check_ownership(@activation_rule, activation_rules_url)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activation_rule_params
    params.
      require(:activation_rule).
      permit(
        :name,
        :description,
        :activation_params_attributes => [
            :id,
            :api_param_id,
            :value
          ]
        )
  end
end

app/helpers/activation_rules_helper.rb
module ActivationRulesHelper
  
  def create_options(activation_param)
    options = {}

    if !activation_param.api_param.accepted_values.blank?
      options.merge!(collection: activation_param.api_param.accepted_values.map(&:value))
    elsif activation_param.api_param.data_type.name == 'boolean'
      options.merge!(as: :radio_buttons)
    elsif activation_param.api_param.data_type.name == 'date'
      options.merge!(as: :date, html5: true)
      options.merge!(value: localize(activation_param.value.to_date)) unless activation_param.value.blank?
    elsif activation_param.api_param.name == 'group_name'
      options.merge!(readonly: true)
    end
    
    return options
  end

end

app/views/activation_rules/_activation_param_fields.html.erb
<%- api_param = f.object.api_param -%>
<%- activation_param = f.object -%>
<div class="row form-group">
  <div class="col-md-5">
    <%= link_to '?', '#', "data-toggle" => "tooltip",
                          title: activation_param.api_param.description,
                          "data-placement" => "top" %>
    <%= f.label activation_param.api_param.name %>
    <%= f.input_field :api_param_id, as: :hidden, value: activation_param.api_param.id %>
  </div>
  <div class="col-md-7">
    <%= f.input_field :value, create_options(activation_param).merge!(value: activation_param.value) %>
  </div>
</div>

app/views/activation_rules/_form.html.erb
<%= simple_form_for @activation_rule, :html => { :class => "form-vertical" },
  wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean
  } do |f| %>

  <div class="col-sm-7">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.simple_fields_for :activation_params, @activation_rule.activation_params do |builder| %>
      <%= render 'activation_param_fields', f: builder %>
    <% end %>

    <%= f.submit nil, :class => 'btn btn-primary', value: 'Update' %>
    <%= link_to 'Cancelar', activation_rules_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/activation_rules/edit.html.erb
<%- model_class = @activation_rule_name.constantize -%>
<div class="page-header">
  <h1>Editar Regra Hotmart</h1>
</div>

<%= render 'form' %>

app/views/activation_rules/index.html.erb
<%- model_class = @activation_rule_name.constantize -%>
<div class="page-header">
  <h1>Regras Hotmart</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped" id='data_table'>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th class="col-sm-3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @activation_rules.each do |rule| %>
        <tr>
          <td><%= rule.name %></td>
          <td><%= rule.description %></td>
          <td>
            <%= link_to 'Exibir', rule, class: 'btn btn-success btn-xs'  %>
            <%= link_to 'Editar', edit_activation_rule_path(rule), :class => 'btn btn-default btn-xs' %>
            <%= link_to 'Duplicar', new_activation_rule_path(id: rule.id), :class => 'btn btn-warning btn-xs' %>
            <%= link_to 'Excluir', rule,
                        :method => :delete,
                        :data => { :confirm => 'Tem certeza?' },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div

<br />

<%= link_to 'Novo', new_activation_rule_path, :class => 'btn btn-primary', id: 'botao_novo' %>

app/views/activation_rules/new.html.erb
<%- model_class = @activation_rule_name.constantize -%>
<div class="page-header">
  <h1>Nova Regra Hotmart</h1>
</div>

<%= render 'form' %>

app/views/activation_rules/show.html.erb
<%- model_class = @activation_rule_name.constantize -%>
<div class="page-header">
  <h1>Exibir Regra Hotmart</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @activation_rule.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @activation_rule.description %></dd>
  <dt><strong><%= 'Parameters'.humanize %>:</strong></dt>
  <dd></dd>
  <% @activation_rule.activation_params.each do |activation_param| %>
    <dt><strong><%= ApiParam.human_attribute_name(activation_param.api_param.name) %>:</strong></dt>
    <dd><%= (activation_param.api_param.name == 'purchase_date_start' || activation_param.api_param.name == 'purchase_date_end') ? activation_param.value.to_date.try(:strftime, "%d/%m/%Y") : activation_param.value %></dd>
  <% end %>
<dl>

<%= link_to 'Voltar', activation_rules_path, :class => 'btn btn-default' %>
<%= link_to 'Editar', edit_activation_rule_path(@activation_rule), :class => 'btn btn-default' %>
<%= link_to 'Duplicar', new_activation_rule_path(id: @activation_rule.id), :class => 'btn btn-warning' %>
<%= link_to 'Excluir',
              @activation_rule,
              :method => 'delete',
              :data => { :confirm => 'Tem certeza?' },
              :class => 'btn btn-danger' %>