config/routes.rb
Rails.application.routes.draw do
  
  # get 'user/update'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  # Routes for STI api_params
  resources :helpscout_params, controller: 'api_params', type: 'HelpscoutParam'
  resources :hotmart_params, controller: 'api_params', type: 'HotmartParam'
  resources :mailchimp_params, controller: 'api_params', type: 'MailchimpParam'

  # Routes for STI api_keys
  resources :helpscout_api_keys, controller: 'api_keys', type: 'HelpscoutApiKey', only: [:edit, :update]
  resources :hotmart_api_keys, controller: 'api_keys', type: 'HotmartApiKey', only: [:edit, :update]
  resources :mailchimp_api_keys, controller: 'api_keys', type: 'MailchimpApiKey', only: [:edit, :update]

  resources :activation_rules
  get "/mailchimp_actuation_rules/load_group_names", to: 'mailchimp_actuation_rules#load_group_names'
  resources :mailchimp_actuation_rules
  resources :rule_associations

  resources :notifications, only: [:index, :show, :destroy]
  post "/notifications/:token", to: 'notifications#create'
  post "/helpscout_info/:token", to: 'helpscout_info#get_notification', as: 'helpscout_info'

end

app/models/mailchimp_actuation_rule.rb
# == Schema Information
#
# Table name: mailchimp_actuation_rules
#
#  id                 :integer          not null, primary key
#  activation_rule_id :integer
#  api_method_id      :integer
#  name               :string(255)
#  description        :text(255)
#  created_at         :datetime
#  updated_at         :datetime
#  user_id            :integer
#

class MailchimpActuationRule < ActiveRecord::Base
  validates_presence_of :name, :description
  validates_uniqueness_of :name, scope: :user_id

  belongs_to :api_method
  belongs_to :user

  has_many :rule_associations
  has_many :activation_rules ,through: :rule_associations

  has_many :actuation_params, dependent: :destroy
  has_many :arguments, through: :actuation_params
  accepts_nested_attributes_for :actuation_params#, :reject_if => lambda { |c| c[:value].blank? }

  def run(user, params, rule_id)
    mailchimp = Mailchimp::API.new(user.mailchimp_api_key.first.key)
    method = self.api_method

    case method.name
    when 'subscribe'
      begin
        ap = self.actuation_params
        retorno = mailchimp.lists.subscribe(
          self.arguments.find_by_position(1).actuation_params.where(id: ap.map(&:id)).first.value, # id da lista (*list_id)
          { email: params[:email] },                                                               # o e-mail a ser cadastrado (extraído de params) (*email)
          mount_groupings(params[:email], params[:transaction]),                                                                         # o nome dos grupos (*group_name)
          self.arguments.find_by_position(4).actuation_params.where(id: ap.map(&:id)).first.value, # o tipo de email (text ou html) (*email_type)
          self.arguments.find_by_position(5).actuation_params.where(id: ap.map(&:id)).first.value, # utilizar ou não double opt-in (*double_optin)
          self.arguments.find_by_position(6).actuation_params.where(id: ap.map(&:id)).first.value, # permitir atualização de informações de usuário que já esteja cadastrado na lista (*update_existing)
          self.arguments.find_by_position(7).actuation_params.where(id: ap.map(&:id)).first.value, # sobrescrever grupos de interesse ou adicionar os fornecidos aos atuais (*replace_interests)
          self.arguments.find_by_position(8).actuation_params.where(id: ap.map(&:id)).first.value  # envia email de boas vindas (*send_welcome)
          )
      rescue => e
        logger.info "**************Exceção lançada no método subscribe do Mailchimp***************"
        return build_returning(:error, e.message, rule_id)
      else
        logger.info "**************Retorno considerado sucesso no método subscribe do Mailchimp***************"
        logger.info retorno
        return build_returning(:success, "E-mail cadastrado na lista com sucesso", rule_id)
      end
    when 'unsubscribe'
      begin
        ap = self.actuation_params
        retorno = mailchimp.lists.unsubscribe(
          self.arguments.find_by_position(1).actuation_params.where(id: ap.map(&:id)).first.value, # id da lista (*list_id)
          { email: params[:email] }, # o e-mail a ser cadastrado (extraído de params) (*email)
          self.arguments.find_by_position(3).actuation_params.where(id: ap.map(&:id)).first.value, # o tipo de email (text ou html) (*email_type)
          self.arguments.find_by_position(4).actuation_params.where(id: ap.map(&:id)).first.value, # utilizar ou não double opt-in (*double_optin)
          self.arguments.find_by_position(5).actuation_params.where(id: ap.map(&:id)).first.value
          )
      rescue => e
        logger.info "**************Exceção lançada no método unsubscribe do Mailchimp***************"
        logger.info retorno
        return build_returning(:error, e.message, rule_id)
      else
        logger.info "**************Retorno considerado sucesso no método unsubscribe do Mailchimp***************"
        logger.info retorno
        return build_returning(:success, "E-mail descadastrado da lista com sucesso", rule_id)
      end
    when  'update'
      begin
        ap = self.actuation_params
        retorno = mailchimp.lists.update_member(
          self.arguments.find_by_position(1).actuation_params.where(id: ap.map(&:id)).first.value, # id da lista (*list_id)
          params[:email],
          mount_groupings(params[:email], params[:transaction]),                                                                         # o nome dos grupos (*group_name)
          self.arguments.find_by_position(3).actuation_params.where(id: ap.map(&:id)).first.value, # o tipo de email (text ou html) (*email_type)
          self.arguments.find_by_position(4).actuation_params.where(id: ap.map(&:id)).first.value  # sobrescrever grupos de interesse ou adicionar os fornecidos aos atuais (*replace_interests)
          )
      rescue => e
        logger.info "**************Exceção lançada no método update do Mailchimp***************"
        logger.info retorno
        return build_returning(:error, e.message, rule_id)
      else
        logger.info "**************Retorno considerado sucesso no método update do Mailchimp***************"
        logger.info retorno
        return build_returning(:success, "Atualizado com sucesso", rule_id)
      end
    end
  end

  def self.mount_by_method(method, user)
    method_arguments = method.arguments
    mailchimp_api = Mailchimp::API.new(user.mailchimp_api_key.first.key)

    case method.name
    when 'subscribe'
     mount_subscribe(method_arguments, mailchimp_api)
    when 'unsubscribe'
     mount_unsubscribe(method_arguments, mailchimp_api)
    when 'update-member'
     mount_update_member(method_arguments, mailchimp_api)
    end
  end

  private

  def mount_groupings(email, transac)
    byebug
    ap = self.actuation_params
    params = self.arguments.find_by_position('3').actuation_params.where(id: ap.map(&:id)).where("actuation_params.value IS NOT NULL")
    list_groupings = params.map(&:value) unless params.blank? # pegando lista de ids da lista e ids dos grupos no formato "listid_groupid"
    groupings = []
    
    while !list_groupings.blank?
      groups = []
      list_id = list_groupings.first.split("_").first
      list_id_regex = Regexp.new(list_id+"_") # pegando "listid_" do primeiro elemento do array
      lg_by_list_id = list_groupings.select { |lg| lg =~ list_id_regex } # pegando todos os elementos da mesma lista
      list_groupings -= lg_by_list_id # removendo os elementos do array
      lg_by_list_id.each do |lg|
        group = lg.split(/(?=_).(.*)/).second.tr("_", " ")
        groups << group
      end
      groupings << { id: list_id, groups: groups }
    end

    if groupings.blank?
      return nil
    else
      grps =  { 'groupings' => groupings }
      grps.merge!('TRANS_HOT' => transac) if self.arguments.find_by_position(5).actuation_params.where(id: ap.map(&:id)).first.value
      return grps
    end
  end

  def self.mount_subscribe(arguments, mailchimp_api)
    arguments.each do |argument|
      api_param = argument.api_param
      if api_param.name == 'list_id'
        listas = mailchimp_api.lists.list
        api_param.accepted_values = listas["data"].map do |data|
                                      AcceptedValue.new(
                                        { value: data["id"],
                                          placeholder: data["name"]
                                        }
                                      )
                                    end       
      # elsif api_param.name == 'group_name'
      #  group_names = mailchimp_api.lists.interest_groupings 
      end
    end
  end

  def self.mount_unsubscribe(arguments, mailchimp_api)
    arguments.each do |argument|
      api_param = argument.api_param
       if api_param.name == 'list_id'
        listas = mailchimp_api.lists.list
        api_param.accepted_values = listas["data"].map do |data|
                                      AcceptedValue.new(
                                        { value: data["id"],
                                          placeholder: data["name"]
                                        }
                                      )
                                    end
      # elsif api_param.name == 'group_name'
      #  group_names = mailchimp_api.lists.interest_groupings 
      end
    end
  end

  def self.mount_update_member(arguments, mailchimp_api)
    arguments.each do |argument|
      api_param = argument.api_param
      
      if api_param.name == 'list_id'
        listas = mailchimp_api.lists.list
        api_param.accepted_values = listas["data"].map do |data|
                                      AcceptedValue.new(
                                        { value: data["id"],
                                          placeholder: data["name"]
                                        }
                                      )
                                    end
      # elsif api_param.name == 'group_name'
      #  group_names = mailchimp_api.lists.interest_groupings 
      end
     end
  end

  def build_returning(msg_type, msg, rule_id)
    h = Hash.new
    h.store(:name, self.name)
    h.store(:activation_rule, rule_id)
    h.store(msg_type, msg)
    return h
  end
end

app/controllers/mailchimp_actuation_rules_controller.rb
class MailchimpActuationRulesController < ApplicationController
  layout 'client'
  before_action :set_mailchimp_actuation_rule, only: [:show, :edit, :update, :destroy]
  before_action :check_whether_api_key_was_created

  # GET /actuation_rules
  # GET /actuation_rules.json
  def index
    @mailchimp_actuation_rules = current_user.
                                  mailchimp_actuation_rules.
                                  all
  end

  # GET /actuation_rules/1
  # GET /actuation_rules/1.json
  def show
  end

  # GET /actuation_rules/new
  def new
    if params[:id].blank?
      @mailchimp_actuation_rule = MailchimpActuationRule.new
      params[:method].blank? ? force_user_choose_an_api_method : build_api_method_arguments
    else
      @mailchimp_actuation_rule = MailchimpActuationRule.find_by_id(params[:id])
      @method = @mailchimp_actuation_rule.api_method
    end
  end

  # GET /actuation_rules/1/edit
  def edit
  end

  # POST /actuation_rules
  # POST /actuation_rules.json
  def create
    @mailchimp_actuation_rule = current_user.
                                  mailchimp_actuation_rules.
                                  new(mailchimp_actuation_rule_params)

    respond_to do |format|
      if @mailchimp_actuation_rule.save
        format.html { redirect_to @mailchimp_actuation_rule,
                                  notice: 'Regra Mailchimp criada com sucesso.' }
        format.json { render :show,
                              status: :created,
                              location: @mailchimp_actuation_rule }
      else
        @method = @mailchimp_actuation_rule.api_method
        format.html { render :new }
        format.json { render json: @mailchimp_actuation_rule.errors,
                              status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actuation_rules/1
  # PATCH/PUT /actuation_rules/1.json
  def update
    respond_to do |format|
      if @mailchimp_actuation_rule.update(mailchimp_actuation_rule_params)
        format.html { redirect_to @mailchimp_actuation_rule, 
                                  notice: 'Regra Mailchimp atualizada com sucesso.' }
        format.json { render :show,
                              status: :ok,
                              location: @mailchimp_actuation_rule }
      else
        format.html { render :edit }
        format.json { render json: @mailchimp_actuation_rule.errors,
                              status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actuation_rules/1
  # DELETE /actuation_rules/1.json
  def destroy
    @mailchimp_actuation_rule.destroy
    respond_to do |format|
      format.html { redirect_to @mailchimp_actuation_rule, 
                                  notice: 'Regra Mailchimp excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  # AJAX GET "/load_group_names"
  def load_group_names
    mc = Mailchimp::API.new(current_user.mailchimp_api_key.first.key)
    interestGroupings = mc.lists.interest_groupings(params[:list_id])
    ig_names = interestGroupings.map do |ig|
      ig["groups"].map do |gp|
        { id: "#{ig["id"]}_#{gp["name"].tr(" ","_")}", content: "(#{ig["name"]}) #{gp["name"]}" }
      end
    end

    rescue => e
      render json: ig_names, :status => :unprocessable_entity
    else
      respond_to do |format|
        format.json { render json: ig_names.flatten }
      end
  end

  private

  def check_whether_api_key_was_created
    apiKeyObj = current_user.mailchimp_api_key.first
    redirect_to edit_mailchimp_api_key_path(apiKeyObj.id),
        alert: "Para acessar esta área informe abaixo \
                  sua API Key do Mailchimp." if apiKeyObj.key.blank?
  end

  # Used so that user can choose the api's method
  def force_user_choose_an_api_method
    @api_methods = MailchimpApiMethod.pluck(:id, :name)
  end

  def build_api_method_arguments
    @method = MailchimpApiMethod.find_by_name(params[:method])
    @mailchimp_actuation_rule.arguments = MailchimpActuationRule.
                                            mount_by_method(@method, current_user)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_mailchimp_actuation_rule
    @mailchimp_actuation_rule = current_user.
                                  mailchimp_actuation_rules.
                                  find_by_id(params[:id])
    check_ownership(@mailchimp_actuation_rule, mailchimp_actuation_rule_url)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def mailchimp_actuation_rule_params
    params.require(:mailchimp_actuation_rule).
              permit(
                :name,
                :description,
                :api_method_id,
                :actuation_params_attributes => [
                  :id,
                  :argument_id,
                  :value,
                  :placeholder
                ]
              )
  end
end

app/views/mailchimp_actuation_rules/_actuation_param_fields.html.erb
<div class="row form-group">
  <div class="col-md-3" id=<%= f.object.argument.api_param.name == 'group_name' ? "div_argument_id" : "" %>>
    <%= link_to '?', '#', "data-toggle" => "tooltip",
                          title: f.object.argument.api_param.description,
                          "data-placement" => "top" %>
    <%= f.label f.object.argument.api_param.name %>
    <%= f.input_field :argument_id, as: :hidden, value: f.object.argument_id %>
  </div>
  <div class="col-md-8" id=<%= f.object.argument.api_param.name == 'group_name' ? "div_input_group_name" : "" %> >
    <%= f.input_field :value, create_options_for_actuation_rules(f.object.argument.api_param).merge!(value: f.object.value) unless f.object.argument.api_param.name == 'group_name'  %>
    <%= f.input_field :placeholder, as: :hidden %>
  </div>
  <div class="col-md-1" >
    <%= link_to '#', id: :add_group_name, style: "display:none" do %>
      <%= fa_icon('plus') %>
    <% end if f.object.argument.api_param.name == 'group_name' %>
  </div>
</div>

app/views/mailchimp_actuation_rules/_form.html.erb
<%= simple_form_for @mailchimp_actuation_rule, :html => { :class => "form-vertical" },
  wrapper_mappings: {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean
  } do |f| %>

  <div class="col-sm-10">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input_field :api_method_id, as: :hidden, value: @method.id if @method %>
    <%= f.simple_fields_for :actuation_params, @mailchimp_actuation_rule.actuation_params do |builder| %>
      <%= render 'actuation_param_fields', f: builder %>
    <% end %>
    <%= f.submit nil, :class => 'btn btn-primary', value: 'Update' %>
    <%= link_to 'Cancelar', mailchimp_actuation_rules_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/mailchimp_actuation_rules/edit.html.erb
<%- model_class = MailchimpActuationRule -%>
<div class="page-header">
  <h1>Editar Regra Mailchimp</h1>
</div>

<%= render 'form' %>

app/views/mailchimp_actuation_rules/index.html.erb
<%- model_class = MailchimpActuationRule -%>
<div class="page-header">
  <h1>Regras Mailchimp</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped" id='data_table'>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @mailchimp_actuation_rules.each do |rule| %>
        <tr>
          <td><%= rule.name %></td>
          <td><%= rule.description %></td>
          <td>
            <%= link_to 'Exibir', mailchimp_actuation_rule_path(rule), class: 'btn btn-success btn-xs'  %>
            <%= link_to 'Editar', edit_mailchimp_actuation_rule_path(rule), :class => 'btn btn-default btn-xs' %>
            <%= link_to 'Duplicar', new_mailchimp_actuation_rule_path(id: rule.id), :class => 'btn btn-warning btn-xs' %>
            <%= link_to 'Excluir',
                        mailchimp_actuation_rule_path(rule),
                        :method => :delete,
                        :data => { :confirm => 'Tem certeza?' },
                        :class => 'btn btn-xs btn-danger' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Novo',
            new_mailchimp_actuation_rule_path,
            :class => 'btn btn-primary',
            id: 'botao_novo' %>

app/views/mailchimp_actuation_rules/new.html.erb
<%- model_class = MailchimpActuationRule -%>
<% if @method.blank? && params[:id].blank? %>
  <% @api_methods.each do |method| %>
  <%= link_to method[1],
              new_mailchimp_actuation_rule_path(method: method[1]),
              :class => 'btn btn-primary',
              id: method[1] %>
  <% end %>
<% else %>
  <div class="page-header">
    <h1>Nova Regra Mailchimp - <%= @method.name.titleize %></h1>
  </div>

  <%= render 'form' %>
<% end %>

app/views/mailchimp_actuation_rules/show.html.erb
<%- model_class = MailchimpActuationRule -%>
<div class="page-header">
  <h1>Exibir Regra Mailchimp</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @mailchimp_actuation_rule.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @mailchimp_actuation_rule.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:api_method_id) %>:</strong></dt>
  <dd><%= @mailchimp_actuation_rule.api_method.name %></dd>
  <% @mailchimp_actuation_rule.actuation_params.each do |param| %>
    <dt><strong><%= ApiParam.human_attribute_name(param.argument.api_param.name) %>:</strong></dt>
    <dd><%= param.placeholder.blank? ? param.value : param.placeholder %></dd>
  <% end %>
<dl>

<%= link_to 'Voltar', mailchimp_actuation_rules_path, :class => 'btn btn-default' %>
<%= link_to 'Editar', edit_mailchimp_actuation_rule_path(@mailchimp_actuation_rule), :class => 'btn btn-default' %>
<%= link_to 'Duplicar', new_mailchimp_actuation_rule_path(id: @mailchimp_actuation_rule.id), :class => 'btn btn-warning' %>
<%= link_to 'Excluir',
            mailchimp_actuation_rule_path(@mailchimp_actuation_rule),
              :method => 'delete',
              :data => { :confirm => 'Tem certeza?' },
              :class => 'btn btn-danger' %>