config/routes.rb
Rails.application.routes.draw do
  
  # get 'user/update'

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  # Routes for STI api_params
  resources :helpscout_params, controller: 'api_params', type: 'HelpscoutParam'
  resources :hotmart_params, controller: 'api_params', type: 'HotmartParam'
  resources :mailchimp_params, controller: 'api_params', type: 'MailchimpParam'

  # Routes for STI api_keys
  resources :helpscout_api_keys, controller: 'api_keys', type: 'HelpscoutApiKey', only: [:edit, :update]
  resources :hotmart_api_keys, controller: 'api_keys', type: 'HotmartApiKey', only: [:edit, :update]
  resources :mailchimp_api_keys, controller: 'api_keys', type: 'MailchimpApiKey', only: [:edit, :update]

  resources :activation_rules
  get "/mailchimp_actuation_rules/load_group_names", to: 'mailchimp_actuation_rules#load_group_names'
  resources :mailchimp_actuation_rules
  resources :rule_associations

  resources :notifications, only: [:index, :show, :destroy]
  post "/notifications/:token", to: 'notifications#create'
  post "/helpscout_info/:token", to: 'helpscout_info#get_notification', as: 'helpscout_info'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Script</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu_links">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(image_tag("e-editora_logo.png", :alt => "E-Editora", id: :logo), root_path) %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="menu_links">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Parâmetros das APIs <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to('Hotmart', hotmart_params_path) %></li>
                <li><%= link_to('MailChimp', mailchimp_params_path) %></li>
                <li><%= link_to('HelpScout', helpscout_params_path) %></li>
                <!-- <li class="divider"></li>
                <li><a href="#">Separated link</a></li> -->
              </ul>
            </li>
            <li><%= link_to t('api.integration'), edit_hotmart_api_key_path(current_user.hotmart_api_key.first.id) %></li>
            <!-- <li class="active"><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul> 
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>

      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Script</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu_links">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(image_tag("e-editora_logo.png", :alt => "E-Editora", id: :logo ), root_path) %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="menu_links">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <button type="button" class="btn btn-default navbar-btn" id="tour">
                <i class="fa fa-play-circle"></i> Iniciar Tutorial
              </button>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <%= link_to 'Sair', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>

      <div class="row">
        <div class="col-sm-3" id="sidebar">
          <ul class='nav nav-sidebar'>
            <li <%= "class = active" if is_active?('api_keys') %> id="integracao">
              <%= link_to 'Integração', edit_hotmart_api_key_path(current_user.hotmart_api_key.first.id) %>
            </li>
            <li <%= "class = active" if is_active?('activation_rules') %> id="regras_hotmart">
              <%= link_to 'Regras Hotmart',
                          activation_rules_path,
                          id: 'regras_hotmart_link' %>
            </li>
            <li <%= "class = active" if is_active?('mailchimp_actuation_rules') %> id="regras_mailchimp">
              <%= link_to 'Regras Mailchimp',
                          mailchimp_actuation_rules_path,
                          id: 'regras_mailchimp_link' %>
            </li>
            <li <%= "class = active" if is_active?('rule_associations') %> id="assoc_regras">
              <%= link_to 'Associação de regras',
                          rule_associations_path,
                          id: 'assoc_regras_link' %>
            </li>
            <li <%= "class = active" if is_active?('notifications') %> id="logs">
              <%= link_to 'Logs',
                          notifications_path,
                          id: 'logs_link' %>
            </li>
          </ul>
        </div>
        <div class="col-sm-9" id="dashboard">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Script</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

      <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to(image_tag("e-editora_logo.png", :alt => "E-Editora", id: :logo), root_path) %>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
  
  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>

      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
  
</html>